[supported]
laptops = ["15ACH6"]
[15ACH6]

check_mode = "echo '\\\\_SB.PCI0.LPC0.EC0.SPMO' > /proc/acpi/call; cat /proc/acpi/call; printf '\\n'"
check_mode_backup = "echo '\\\\_SB.PCI0.LPC0.EC0.GZ44' > /proc/acpi/call; cat /proc/acpi/call; printf '\\n'"
performance_modes ={intelligent_cooling = "echo '\\\\_SB_.GZFD.WMAA 0 0x2C 2' > /proc/acpi/call",extreme_performance = "echo '\\\\_SB_.GZFD.WMAA 0 0x2C 3' > /proc/acpi/call",battery_saving = "echo '\\\\_SB_.GZFD.WMAA 0 0x2C 1' > /proc/acpi/call"}
rapid_charge = { turn_on = "echo '\\\\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x07' > /proc/acpi/call",turn_off = "echo '\\\\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' > /proc/acpi/call",status_check = "echo '\\\\_SB.PCI0.LPC0.EC0.QCHO' > /proc/acpi/call; cat /proc/acpi/call; printf '\\n'"}
battery_conservation = {turn_on = "echo '\\\\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x03' > /proc/acpi/call",turn_off = "echo '\\\\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x05' > /proc/acpi/call",status_check = "echo '\\\\_SB.PCI0.LPC0.EC0.BTSM' > /proc/acpi/call; cat /proc/acpi/call; printf '\\n'"}